name: flutter_vibrate
description: A Haptic Feedback plugin.
version: 1.1.1
environment:
  sdk: '>=2.12.0-259.8.beta <3.0.0'
  flutter: ^1.10.0
authors:
  - Clovis Nicolas <clovisnicolas0@gmail.com>
  - Rhodes Davis Jr. <rody.davis.jr@gmail.com>
  - GiKode <827266641@qq.com>
maintainer: Rody Davis (@rodydavis)
homepage: https://github.com/rodydavis/plugins
repository: https://github.com/rodydavis/flutter_vibrate

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: flutter.plugins.vibrate
        pluginClass: VibratePlugin
      ios:
        pluginClass: VibratePlugin
